name: DEV frontend deployment 
on:
  push:
    branches:
     - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#invoke patch request
      - name: Invoke PATCH request to build and deploy website
        env:
          CICD_API_KEY: ${{ secrets.CICD_API_KEY }}
        run: |
          curl -X PATCH -H "Authorization: Bearer $CICD_API_KEY" ${{ vars.CICD_DEV_URL }}
