name: PROD Frontend Deployment 
on:
  push:
    branches:
     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#invoke patch request
      - name: Invoke PATCH request
        env:
          CICD_API_KEY: ${{ secrets.CICD_API_KEY }}
        run: |
          curl -X PATCH -H "Authorization: Bearer $CICD_API_KEY" ${{ vars.CICD_PROD_URL }}
